import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Adminaside from "@/components/admin/Adminaside";
import Header from "@/components/admin/Header";
import AdminGate from "@/components/admin/AdminGate";
import { Toaster} from 'sonner'

// Admin screens depend on live backend data and must not be prerendered at build time.
export const dynamic = "force-dynamic";


const geistSans = Geist({
  variable: "--font-geist-san",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nestro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="admin-theme">

        <AdminGate><div className="admin-shell flex min-h-screen w-full pb-20 md:pb-0">
        <Toaster position="top-center" richColors/>
          <Adminaside />
          <div className="min-w-0 flex-1">
            <Header />
            {children}
          </div>

        </div></AdminGate>
      </body>
    </html>
  );
}
