import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/website/HFcomponents/Header";
import Footer from "@/components/website/HFcomponents/Footer";
// import Container from "@/components/website/ui/Container";
import Storeprovider from "@/redux/Storeprovider";
import {getMe} from "@/api/api.js"
const geistSans = Geist({
  variable: "--font-geist-san",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nestro",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const response=await getMe();
  // console.log(response,"response")
  
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Storeprovider>

          <Header />
          <main className="w-full flex-1 bg-[#efece6]">
            <div className="w-full max-w-[1580px] mx-auto">
              {children}
            </div>
          </main>
          <Footer />
        </Storeprovider>

      </body>
    </html>
  );
}
